// Loads tests/parity/fixtures/*.json (generated by the Python reference
// engine) into typed inputs the TS engine can run, for the shared parity
// test suite in web/tests/unit/parity.test.ts.
import type { AssetStrategy, EngineEvent, EquitySample, Order, Position, ProductId, Strategy, Tick } from "./model";

export interface ParityFixture {
  name: string;
  roundDp: number;
  bankrollUsd: number;
  moveStopToBreakevenAfterTp1: boolean;
  strategy: Record<string, {
    productId: ProductId;
    enabled: boolean;
    allocationUsd: number;
    stopPrice: number;
    takeProfit: { tp1Price: number; tp1Fraction: number; tp2Price: number; tp2Fraction: number };
    entries: { id: string; price: number; quoteSizeUsd: number }[];
  }>;
  strategyHash: string;
  datasetHash: string;
  ticks: { ts: string; prices: Partial<Record<ProductId, number>> }[];
  expectedOrders: Record<string, unknown>[];
  expectedPositions: Record<string, unknown>[];
  expectedEvents: Record<string, unknown>[];
  expectedEquitySamples: EquitySample[];
  expectedSummary: {
    ending_equity: number;
    max_drawdown: number;
    total_realized_pnl: number;
    stop_count: number;
    tp1_count: number;
    tp2_count: number;
    entries_filled_count: number;
  };
}

export function fixtureToStrategy(fixture: ParityFixture): Strategy {
  const assets: AssetStrategy[] = Object.values(fixture.strategy).map((a) => ({
    productId: a.productId,
    enabled: a.enabled,
    allocationUsd: a.allocationUsd,
    stopPrice: a.stopPrice,
    takeProfit: a.takeProfit,
    entries: a.entries,
  }));
  return {
    schemaVersion: 1,
    name: fixture.name,
    bankrollUsd: fixture.bankrollUsd,
    quoteCurrency: "USD",
    assets,
    moveStopToBreakevenAfterTp1: fixture.moveStopToBreakevenAfterTp1,
    createdAt: "1970-01-01T00:00:00.000Z",
    updatedAt: "1970-01-01T00:00:00.000Z",
  };
}

export function fixtureTicks(fixture: ParityFixture): Tick[] {
  const out: Tick[] = [];
  for (const t of fixture.ticks) {
    for (const [productId, price] of Object.entries(t.prices)) {
      out.push({ ts: t.ts, productId: productId as ProductId, price: price! });
    }
  }
  return out;
}

const BOOTSTRAP_PLACEHOLDER = "BOOTSTRAP_TS";

/** Replaces the wall-clock bootstrap timestamp with a fixed placeholder so
 * a freshly-run scenario can be deep-equal-compared against a fixture
 * generated at a different time. See tests/parity/README.md. */
export function normalizeForComparison<T>(value: T, bootstrapTs: string): T {
  const text = JSON.stringify(value).split(bootstrapTs).join(BOOTSTRAP_PLACEHOLDER);
  return JSON.parse(text) as T;
}

export function roundTo(value: number, dp: number): number {
  const factor = 10 ** dp;
  return Math.round(value * factor) / factor;
}

export function deepRound<T>(value: T, dp: number): T {
  if (typeof value === "number") return roundTo(value, dp) as unknown as T;
  if (Array.isArray(value)) return value.map((v) => deepRound(v, dp)) as unknown as T;
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = deepRound(v, dp);
    return out as T;
  }
  return value;
}

export type { Order, Position, EngineEvent };
